title: My First Blog
author: Justin Holiday
email: jus1185@yahoo.com
description: > # this means to ignore newlines until "baseurl:"
  The programming journey continues as I develop new skills sets to add to my toolbox. This will lead to opportuinities that let me explore my passions.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
